### ISSUE TITLE
avoidance vs avoiding (and some general readme stuff)

### ISSUE THREAD

**Issue by Arne-Berner** [andriyDev/dodgy#9]
The readme uses .compute_avoidance_velocity(...) on agents, but the function is called .compute_avoiding_velocity(...). You might want to change one of the two names. 
Also it doubles time horizon and obstacle time horizon in that function call.
Then there is "new velocities" which is not mutable, even though something gets pushed to it. 
I mean those are some minor issues and most people who will find this repository will know how to work with it, but maybe you'll have some time later on.

Also I'm not sure, but isn't preferred velocity, the same as the velocity given in the agent?

**Comment by andriyDev** [comment]
Ah thank you! Tbh I didn't notice these.

I also initially couldn't find out how to get my README in my code. Turns out its `#![doc = include_str!("../README.md")]`. Working on a PR to fix this up.

I don't really understand what you mean by the preferred velocity being the same as the velocity given in the agent. If you mean in general (not specific to the README example), the velocity you pass to the agent should be the actual velocity of the character, including avoidance and collisions and whatever else. The preferred velocity is where you want the agent to actually go, which is usually towards some target point.
